name: gvxr-validation
channels:
    - conda-forge
dependencies:
    - python=3.9
    - ipython
    - ipykernel
    - numpy
    - pandas
    - libtiff
    - vtk
    - jupyterlab>=3
    - ipywidgets>=7.6
#    - cma
#    - tomopy
    - scikit-learn
    - scikit-image
#    - scipy
#    - imageio
    - SimpleITK
    - k3d
    - numpy-stl
    - gputil
    - python-kaleido
    - plotly
    - matplotlib
    - py-cpuinfo
    - pip
    - pip:
#        - viewscad
        - git+https://bitbucket.org/spekpy/spekpy_release.git
        - pymoo
#        - chart_studio
        - gvxr
        - opencv-python
